In [5]:
import pandas as pd

docs = pd.read_parquet("legal_clean_html.parquet")

In [24]:
legal_content = docs[
    [
        "id",
        "text"
    ]
]

legal_content.to_parquet(
    "legal_content.parquet",
    index=False
)

In [6]:
docs.columns.tolist()

['id',
 'title',
 'so_ky_hieu',
 'ngay_ban_hanh',
 'loai_van_ban',
 'ngay_co_hieu_luc',
 'ngay_het_hieu_luc',
 'nguon_thu_thap',
 'ngay_dang_cong_bao',
 'nganh',
 'linh_vuc',
 'co_quan_ban_hanh',
 'chuc_danh',
 'nguoi_ky',
 'pham_vi',
 'thong_tin_ap_dung',
 'tinh_trang_hieu_luc',
 'year',
 'html_length',
 'text']

In [7]:
from datasets import load_dataset

rels = load_dataset(
    "th1nhng0/vietnamese-legal-documents",
    "relationships",
    split="data"
)

c:\Users\LAPTOP\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [15]:
from datasets import load_dataset

meta = load_dataset(
    "th1nhng0/vietnamese-legal-documents",
    "metadata",
    split="data"
)

In [16]:
meta_df = meta.to_pandas()
rels_df = rels.to_pandas()

In [23]:
meta_df.to_parquet(
    "legal_metadata.parquet",
    index=False
)

In [17]:
graph = rels_df.merge(
    meta_df,
    left_on="doc_id",
    right_on="id",
    how="left"
)

graph = graph.rename(columns={
    "title": "doc_title",
    "so_ky_hieu": "doc_so_ky_hieu",
    "ngay_ban_hanh": "doc_ngay_ban_hanh",
    "loai_van_ban": "doc_loai_van_ban",
    "ngay_co_hieu_luc": "doc_ngay_co_hieu_luc",
    "ngay_het_hieu_luc": "doc_ngay_het_hieu_luc",
    "nganh": "doc_nganh",
    "linh_vuc": "doc_linh_vuc",
    "co_quan_ban_hanh": "doc_co_quan_ban_hanh",
    "tinh_trang_hieu_luc": "doc_tinh_trang_hieu_luc",
    "year": "doc_year"
})

graph = graph.drop(columns=["id"])

In [18]:
graph.head()

,doc_id,other_doc_id,relationship,doc_title,doc_so_ky_hieu,doc_ngay_ban_hanh,doc_loai_van_ban,doc_ngay_co_hieu_luc,doc_ngay_het_hieu_luc,nguon_thu_thap,ngay_dang_cong_bao,doc_nganh,doc_linh_vuc,doc_co_quan_ban_hanh,chuc_danh,nguoi_ky,pham_vi,thong_tin_ap_dung,doc_tinh_trang_hieu_luc
0,4260,10420,Văn bản căn cứ,Về việc chuyển giao nhiệm vụ quản lý Nhà nước ...,87/1999/QĐ-UB,12/07/1999,Quyết định,12/07/1999,NaN,STP tỉnh Lâm Đồng;,...,NaN,NaN,UBND tỉnh Lâm Đồng,Q.Chủ tịch,Đặng Đức Lợi,Lâm Đồng,NaN,Còn hiệu lực
1,4280,7245,Văn bản căn cứ,Về viẹc quản lý và quy định thống nhất phí chợ...,157/1999/QĐ-UB,19/11/1999,Quyết định,19/11/1999,NaN,STP tỉnh Lâm Đồng;,...,Tài chính,NaN,UBND tỉnh Lâm Đồng,Phó Chủ tịch,Trương Thành Trung,Lâm Đồng,NaN,Còn hiệu lực
2,4263,10420,Văn bản căn cứ,Về việc xử lý đối với quỹ nhà thuộc quyền sở h...,163/1999/QĐ-UB,30/11/1999,Quyết định,30/11/1999,NaN,STP tỉnh Lâm Đồng;,...,Xây dựng,NaN,UBND tỉnh Lâm Đồng,Q.Chủ tịch,Đặng Đức Lợi,Lâm Đồng,NaN,Còn hiệu lực
3,77,195,Văn bản hết hiệu lực,Sắc lệnh bãi bỏ Sắc lệnh 106 ngày 09-09-1949 v...,83/SL,22/05/1950,Sắc lệnh,01/05/1950,NaN,Hồ sơ số Q009-H002A/LTQG;,...,NaN,NaN,Chủ tịch nước,Chủ tịch nước,Hồ Chí Minh,NaN,NaN,Hết hiệu lực toàn bộ
4,77,65,Văn bản bổ sung,Sắc lệnh bãi bỏ Sắc lệnh 106 ngày 09-09-1949 v...,83/SL,22/05/1950,Sắc lệnh,01/05/1950,NaN,Hồ sơ số Q009-H002A/LTQG;,...,NaN,NaN,Chủ tịch nước,Chủ tịch nước,Hồ Chí Minh,NaN,NaN,Hết hiệu lực toàn bộ

In [20]:
meta_df["id"] = meta_df["id"].astype(str)

graph["doc_id"] = graph["doc_id"].astype(str)
graph["other_doc_id"] = graph["other_doc_id"].astype(str)

In [21]:
graph = graph.merge(
    meta_df,
    left_on="other_doc_id",
    right_on="id",
    how="left",
    suffixes=("", "_other")
)

In [22]:
graph.head()

,doc_id,other_doc_id,relationship,doc_title,doc_so_ky_hieu,doc_ngay_ban_hanh,doc_loai_van_ban,doc_ngay_co_hieu_luc,doc_ngay_het_hieu_luc,nguon_thu_thap,...,nguon_thu_thap_other,ngay_dang_cong_bao_other,nganh,linh_vuc,co_quan_ban_hanh,chuc_danh_other,nguoi_ky_other,pham_vi_other,thong_tin_ap_dung_other,tinh_trang_hieu_luc
0,4260,10420,Văn bản căn cứ,Về việc chuyển giao nhiệm vụ quản lý Nhà nước ...,87/1999/QĐ-UB,12/07/1999,Quyết định,12/07/1999,NaN,STP tỉnh Lâm Đồng;,...,Công báo số 16,31/08/1994,NaN,NaN,Quốc hội,Chủ tịch Quốc hội,Nông Đức Mạnh,Toàn quốc,NaN,Hết hiệu lực toàn bộ
1,4280,7245,Văn bản căn cứ,Về viẹc quản lý và quy định thống nhất phí chợ...,157/1999/QĐ-UB,19/11/1999,Quyết định,19/11/1999,NaN,STP tỉnh Lâm Đồng;,...,Công báo điện tử;,...,Tài chính,NaN,Chính phủ,Phó Thủ tướng,Nguyễn Tấn Dũng,Toàn quốc,NaN,Hết hiệu lực toàn bộ
2,4263,10420,Văn bản căn cứ,Về việc xử lý đối với quỹ nhà thuộc quyền sở h...,163/1999/QĐ-UB,30/11/1999,Quyết định,30/11/1999,NaN,STP tỉnh Lâm Đồng;,...,Công báo số 16,31/08/1994,NaN,NaN,Quốc hội,Chủ tịch Quốc hội,Nông Đức Mạnh,Toàn quốc,NaN,Hết hiệu lực toàn bộ
3,77,195,Văn bản hết hiệu lực,Sắc lệnh bãi bỏ Sắc lệnh 106 ngày 09-09-1949 v...,83/SL,22/05/1950,Sắc lệnh,01/05/1950,NaN,Hồ sơ số Q009-H002A/LTQG;,...,Hồ sơ số Q008-H002A/LTQG;,...,NaN,NaN,Chủ tịch nước Việt Nam Dân chủ cộng hoà,Chủ tịch nước,Hồ Chí Minh,Toàn quốc,NaN,Hết hiệu lực toàn bộ
4,77,65,Văn bản bổ sung,Sắc lệnh bãi bỏ Sắc lệnh 106 ngày 09-09-1949 v...,83/SL,22/05/1950,Sắc lệnh,01/05/1950,NaN,Hồ sơ số Q009-H002A/LTQG;,...,Hồ sơ số Q010-H002A/LTQG;,...,NaN,NaN,Chủ tịch nước,Chủ tịch nước,Hồ Chí Minh,NaN,NaN,Hết hiệu lực toàn bộ

In [9]:
print(rels_df.columns.tolist())

['doc_id', 'other_doc_id', 'relationship']

In [14]:
graph = rels_df.merge(
    docs,
    left_on="doc_id",
    right_on="id",
    how="left"
)

graph = graph.rename(columns={
    "title":"doc_title",
    "text":"doc_text",
    "so_ky_hieu":"doc_so_ky_hieu",
    "linh_vuc":"doc_linh_vuc",
    "co_quan_ban_hanh":"doc_co_quan",
    "tinh_trang_hieu_luc":"doc_hieu_luc",
    "year":"doc_year"
})

graph = graph.drop(columns=["id"])

ArrowMemoryError: realloc of size 22952197632 failed

In [ ]:
graph.head()

In [3]:
print("===== HTML =====")
print(docs.loc[0, "content_html"][:1000])

print("\n===== TEXT =====")
print(docs.loc[0, "text"][:1000])

===== HTML =====
<table class="detailcontent" width="100%" border="0" id="content">
                <tr>
                    <td colspan="3">
                        <div align="justify">
                            <p>

</p>
<p>

</p>
<p>
	</p><title></title>

<p align="CENTER">
	<b><font face="Times New Roman" size="5">SẮC LỆNH</font></b></p>
<p align="CENTER">
	<b><font face="Times New Roman" size="2">CỦA CHỦ TỊCH PHỦ NƯỚC VIỆT NAM DÂN CHỦ CỘNG HOÀ</font></b></p>
<p align="CENTER">
	<b><font face="Times New Roman" size="2">SỐ 103/SL NGÀY 5 THÁNG 6 NĂM 1950</font></b></p>
<p align="CENTER">
	 </p>
<p align="CENTER">
	<font face="Times New Roman" size="2">CHỦ TỊCH NƯỚC VIỆT NAM DÂN CHỦ CỘNG HOÀ </font></p>
<p align="CENTER">
	 </p>
<p align="JUSTIFY">
	<i><font color="#0000ff" face="Times New Roman">Chiểu sắc lệnh số 63-SL ngày 22 tháng 11 năm 1945 và các sắc lệnh quy lệ tiếp sau thành lập và tổ chức chính quyền nhân dân;</font></i></p>
<p align="JUSTIFY">
	<i><font color="#0000ff" face="Times N

===== TEXT =====
SẮC LỆNH CỦA CHỦ TỊCH PHỦ NƯỚC VIỆT NAM DÂN CHỦ CỘNG HOÀ SỐ 103/SL NGÀY 5 THÁNG 6 NĂM 1950 CHỦ TỊCH NƯỚC VIỆT NAM DÂN CHỦ CỘNG HOÀ Chiểu sắc lệnh số 63-SL ngày 22 tháng 11 năm 1945 và các sắc lệnh quy lệ tiếp sau thành lập và tổ chức chính quyền nhân dân; Chiểu các sắc lệnh số 254-SL ngày 19 tháng 11 năm 1948 và số 255-SL ngày 19 tháng 11 năm 1948 tổ chức chính quyền nhân dân trong thời kỳ kháng chiến; Theo đề nghị của Phó Thủ tướng Chính phủ; Theo quyết nghị của Hội đồng Chính phủ sau khi Ban Thường trực Quốc hội thoả thuận; RA SẮC LỆNH: Điều 1: Uỷ ban kháng chiến hành chính các cấp có nhiệm vụ lãnh đạo và điều khiển các ngành chuyên môn cấp tương đương. Điều 2: Các điều khoản trái với sắc lệnh này đều bãi bỏ. Điều 3: Một thông tư của Thủ tướng Chính phủ sẽ quy định chi tiết thi hành sắc lệnh này. Điều 4: Ông Thủ tướng Chính phủ và các vị Bộ trưởng chiểu sắc lệnh thi hành. Hồ Chí Minh (Đã ký)

In [4]:
docs_clean = docs.drop(columns=["content_html"])

docs_clean.to_parquet(
    "legal_clean_html.parquet",
    index=False
)